# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: metrics.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='metrics.proto',
  package='metrics',
  syntax='proto3',
  serialized_options=b'Z\007metrics',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rmetrics.proto\x12\x07metrics\"A\n\nMetricData\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01\x12\x11\n\tsource_id\x18\x03 \x01(\t\"7\n\x0fMetricDataBatch\x12$\n\x07metrics\x18\x01 \x03(\x0b\x32\x13.metrics.MetricDataB\tZ\x07metricsb\x06proto3'
)




_METRICDATA = _descriptor.Descriptor(
  name='MetricData',
  full_name='metrics.MetricData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='metrics.MetricData.timestamp', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='metrics.MetricData.value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='source_id', full_name='metrics.MetricData.source_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=91,
)


_METRICDATABATCH = _descriptor.Descriptor(
  name='MetricDataBatch',
  full_name='metrics.MetricDataBatch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='metrics', full_name='metrics.MetricDataBatch.metrics', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=148,
)

_METRICDATABATCH.fields_by_name['metrics'].message_type = _METRICDATA
DESCRIPTOR.message_types_by_name['MetricData'] = _METRICDATA
DESCRIPTOR.message_types_by_name['MetricDataBatch'] = _METRICDATABATCH
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MetricData = _reflection.GeneratedProtocolMessageType('MetricData', (_message.Message,), {
  'DESCRIPTOR' : _METRICDATA,
  '__module__' : 'metrics_pb2'
  # @@protoc_insertion_point(class_scope:metrics.MetricData)
  })
_sym_db.RegisterMessage(MetricData)

MetricDataBatch = _reflection.GeneratedProtocolMessageType('MetricDataBatch', (_message.Message,), {
  'DESCRIPTOR' : _METRICDATABATCH,
  '__module__' : 'metrics_pb2'
  # @@protoc_insertion_point(class_scope:metrics.MetricDataBatch)
  })
_sym_db.RegisterMessage(MetricDataBatch)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
